Repository StudyCrew/StudyCrew, pull requests merged in 2024-01, with the labels that each got.

#126 Merge 77-github-action-playwright
  .env.vault
  .github/workflows/playwright.yml
  package.json
  playwright.config.ts
  tests/homepage/homepage.spec.ts
Labels: bug, Unit test

#120 Merge 78-layout-mobile-overflow into develop
  components/Features/Features.css
  components/Features/Features.tsx
  components/Hero/Hero.css
  components/Hero/Hero.tsx
Labels: bug, UX/UI

#119 Merge 101-mobile-nav-links into develop
  lib/hooks/scrollTo.ts
Labels: bug

#127 Merge 121-mobile-button-width into develop
  components/Button/Button.css
Labels: UX/UI

#181 Merge 180-lint-home-page-tests-semicolon into develop
  tests/homepage/homepage.spec.ts
Labels: Refactor, Unit test

#184 Merge 183-middleware-clerkjs-sentry-monitoring-blocked-by-auth into develop
  middleware.ts
Labels: bug

#201 Feature: Google Analytics Tag
  .env.example
  app/(auth)/layout.tsx
  app/(root)/layout.tsx
  declarations.d.ts
  package.json
  pnpm-lock.yaml
Labels: feature, front-end

#210 Update Mission.tsx
  components/Mission/Mission.tsx
Labels: front-end

#179 Merge 178-components-base-mantine-remove-from-project into develop
  app/(auth)/onboarding/[[...onboarding]]/page.tsx
  app/(root)/layout.tsx
  components/forms/AccountProfile.tsx
  package.json
  pnpm-lock.yaml
  postcss.config.js
Labels: dependencies, Refactor

#202 Refactor: Component Structure
  app/(root)/page.tsx
  components/Button/const.ts
  components/Button/index.tsx
  components/Button/style.css
  components/Button/types.ts
  components/FAQs/const.ts
  components/FAQs/index.tsx
  components/FAQs/style.css
  components/FAQs/types.ts
  components/Features/index.tsx
  components/Features/style.css
  components/Footer/index.tsx
  components/Footer/types.ts
  components/Header/index.tsx
  components/Header/style.css
  components/Header/types.ts
  components/Hero/index.tsx
  components/Hero/style.css
  components/Hero/types.ts
  components/Mission/index.tsx
  components/Mission/style.css
  components/Navbar/index.tsx
  components/Navbar/style.css
  components/Navbar/types.ts
  components/Project/index.tsx
  components/Project/style.css
  components/SignUp/index.tsx
  components/SignUp/style.css
  components/Team/index.tsx
  components/Team/style.css
Labels: Refactor, front-end

#182 Merge 8-framework-head-migrate-from-head-to-metadata-api into develop
  app/(auth)/layout.tsx
  app/(auth)/sign-in/[[...sign-in]]/page.tsx
  app/(auth)/sign-up/[[...sign-up]]/page.tsx
Labels: bug, Refactor

#220 Merge 219-lintprettier-account-profile-resolve-linting-issues-in-account-profile-file into develop
  app/(auth)/layout.tsx
  app/(auth)/onboarding/[[...onboarding]]/page.tsx
  app/(auth)/sign-in/[[...sign-in]]/page.tsx
  app/(auth)/sign-up/[[...sign-up]]/page.tsx
  app/(root)/layout.tsx
  components/forms/AccountProfile.tsx
Labels: Refactor

#228 Feature: Update Footer Design
  app/(root)/page.tsx
  components/Footer/index.tsx
  lib/models/waitlist.ts
Labels: feature, front-end
